preset: psr2

enabled:
  - newline_after_open_tag
  - ordered_use
  - short_array_syntax
  - single_blank_line_before_namespace
  - single_quote
  - unalign_double_arrow
  - unalign_equals
  - unused_use
